name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create generated folder
        run: mkdir -p generated

      - name: Download overview stats
        run: |
          curl -o generated/overview.svg "https://github-readme-stats.vercel.app/api?username=jessica-re88&show_icons=true&theme=radical"

      - name: Download languages stats
        run: |
          curl -o generated/languages.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=jessica-re88&layout=compact&theme=radical"

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add generated/overview.svg generated/languages.svg
          git commit -m "update stats" || echo "No changes to commit"
          git push
